export const ADD_INGRIDIENTS = "ADD_INGRIDIENTS";
export const DELETE_INGRIDIENTS = "DELETE_INGRIDIENTS";
export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";
